name: deploy-container

on:
  // ***** When someone pushes something under packages/container/ folder in the master branch then, start this workflow.
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container                                                  // ******  switch to the packages/container folder

jobs:
  build:
    runs-on: ubuntu-latest                                                                // provision an ubuntu VM

    steps:
      - uses: actions/checkout@v2                                                         // checkout the code
      - run: npm install                                                                  // self-explanatory
      - run: npm run build                                                                //   "

      - uses: chrislennon/action-aws-cli@v1.1                                             // get hold of the AWS CLI
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest     // sync the contents of the dist folder to the S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}                             // AWS authentication credentials
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}                     //      "
